/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AuthedAccountIndexRouteImport } from './routes/_authed/account/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/auth/reset-password.$token'
import { Route as AuthLoginCheckpointRouteImport } from './routes/auth/login.checkpoint'
import { Route as AuthedServerIdRouteImport } from './routes/_authed/server/$id'
import { Route as AuthedAccountSshRouteImport } from './routes/_authed/account/ssh'
import { Route as AuthedAccountApiRouteImport } from './routes/_authed/account/api'
import { Route as AuthedAccountActivityRouteImport } from './routes/_authed/account/activity'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin/settings'
import { Route as AdminAdminServersRouteImport } from './routes/_admin/admin/servers'
import { Route as AdminAdminNodesRouteImport } from './routes/_admin/admin/nodes'
import { Route as AdminAdminNestsRouteImport } from './routes/_admin/admin/nests'
import { Route as AdminAdminMountsRouteImport } from './routes/_admin/admin/mounts'
import { Route as AdminAdminLocationsRouteImport } from './routes/_admin/admin/locations'
import { Route as AdminAdminDatabasesRouteImport } from './routes/_admin/admin/databases'
import { Route as AdminAdminApiRouteImport } from './routes/_admin/admin/api'
import { Route as AdminAdminAllocationsRouteImport } from './routes/_admin/admin/allocations'
import { Route as AdminAdminActivityRouteImport } from './routes/_admin/admin/activity'
import { Route as AuthedServerIdIndexRouteImport } from './routes/_authed/server/$id/index'
import { Route as AdminAdminServersIndexRouteImport } from './routes/_admin/admin/servers/index'
import { Route as AdminAdminNodesIndexRouteImport } from './routes/_admin/admin/nodes/index'
import { Route as AuthedServerIdUsersRouteImport } from './routes/_authed/server/$id/users'
import { Route as AuthedServerIdStartupRouteImport } from './routes/_authed/server/$id/startup'
import { Route as AuthedServerIdShellRouteImport } from './routes/_authed/server/$id/shell'
import { Route as AuthedServerIdSettingsRouteImport } from './routes/_authed/server/$id/settings'
import { Route as AuthedServerIdSchedulesRouteImport } from './routes/_authed/server/$id/schedules'
import { Route as AuthedServerIdNetworkRouteImport } from './routes/_authed/server/$id/network'
import { Route as AuthedServerIdModsRouteImport } from './routes/_authed/server/$id/mods'
import { Route as AuthedServerIdFilesRouteImport } from './routes/_authed/server/$id/files'
import { Route as AuthedServerIdDatabasesRouteImport } from './routes/_authed/server/$id/databases'
import { Route as AuthedServerIdBackupsRouteImport } from './routes/_authed/server/$id/backups'
import { Route as AuthedServerIdActivityRouteImport } from './routes/_authed/server/$id/activity'
import { Route as AdminAdminNodesNewRouteImport } from './routes/_admin/admin/nodes/new'
import { Route as AdminAdminServersViewIdRouteImport } from './routes/_admin/admin/servers/view.$id'
import { Route as AdminAdminNodesViewIdRouteImport } from './routes/_admin/admin/nodes/view.$id'
import { Route as AdminAdminServersViewIdIndexRouteImport } from './routes/_admin/admin/servers/view.$id/index'
import { Route as AdminAdminNodesViewIdIndexRouteImport } from './routes/_admin/admin/nodes/view.$id/index'
import { Route as AdminAdminServersViewIdStartupRouteImport } from './routes/_admin/admin/servers/view.$id/startup'
import { Route as AdminAdminServersViewIdMountsRouteImport } from './routes/_admin/admin/servers/view.$id/mounts'
import { Route as AdminAdminServersViewIdManageRouteImport } from './routes/_admin/admin/servers/view.$id/manage'
import { Route as AdminAdminServersViewIdDetailsRouteImport } from './routes/_admin/admin/servers/view.$id/details'
import { Route as AdminAdminServersViewIdDeleteRouteImport } from './routes/_admin/admin/servers/view.$id/delete'
import { Route as AdminAdminServersViewIdDatabaseRouteImport } from './routes/_admin/admin/servers/view.$id/database'
import { Route as AdminAdminServersViewIdBuildRouteImport } from './routes/_admin/admin/servers/view.$id/build'
import { Route as AdminAdminNodesViewIdSettingsRouteImport } from './routes/_admin/admin/nodes/view.$id/settings'
import { Route as AdminAdminNodesViewIdServersRouteImport } from './routes/_admin/admin/nodes/view.$id/servers'
import { Route as AdminAdminNodesViewIdConfigurationRouteImport } from './routes/_admin/admin/nodes/view.$id/configuration'
import { Route as AdminAdminNodesViewIdAllocationRouteImport } from './routes/_admin/admin/nodes/view.$id/allocation'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedAccountIndexRoute = AuthedAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAccountRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/auth/reset-password/$token',
  path: '/auth/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginCheckpointRoute = AuthLoginCheckpointRouteImport.update({
  id: '/checkpoint',
  path: '/checkpoint',
  getParentRoute: () => AuthLoginRoute,
} as any)
const AuthedServerIdRoute = AuthedServerIdRouteImport.update({
  id: '/server/$id',
  path: '/server/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountSshRoute = AuthedAccountSshRouteImport.update({
  id: '/ssh',
  path: '/ssh',
  getParentRoute: () => AuthedAccountRoute,
} as any)
const AuthedAccountApiRoute = AuthedAccountApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthedAccountRoute,
} as any)
const AuthedAccountActivityRoute = AuthedAccountActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedAccountRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminServersRoute = AdminAdminServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminNodesRoute = AdminAdminNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminNestsRoute = AdminAdminNestsRouteImport.update({
  id: '/nests',
  path: '/nests',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMountsRoute = AdminAdminMountsRouteImport.update({
  id: '/mounts',
  path: '/mounts',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLocationsRoute = AdminAdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminDatabasesRoute = AdminAdminDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminApiRoute = AdminAdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAllocationsRoute = AdminAdminAllocationsRouteImport.update({
  id: '/allocations',
  path: '/allocations',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminActivityRoute = AdminAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthedServerIdIndexRoute = AuthedServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AdminAdminServersIndexRoute = AdminAdminServersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminServersRoute,
} as any)
const AdminAdminNodesIndexRoute = AdminAdminNodesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminNodesRoute,
} as any)
const AuthedServerIdUsersRoute = AuthedServerIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdStartupRoute = AuthedServerIdStartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdShellRoute = AuthedServerIdShellRouteImport.update({
  id: '/shell',
  path: '/shell',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdSettingsRoute = AuthedServerIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdSchedulesRoute = AuthedServerIdSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdNetworkRoute = AuthedServerIdNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdModsRoute = AuthedServerIdModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdFilesRoute = AuthedServerIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdDatabasesRoute = AuthedServerIdDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdBackupsRoute = AuthedServerIdBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdActivityRoute = AuthedServerIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AdminAdminNodesNewRoute = AdminAdminNodesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminAdminNodesRoute,
} as any)
const AdminAdminServersViewIdRoute = AdminAdminServersViewIdRouteImport.update({
  id: '/view/$id',
  path: '/view/$id',
  getParentRoute: () => AdminAdminServersRoute,
} as any)
const AdminAdminNodesViewIdRoute = AdminAdminNodesViewIdRouteImport.update({
  id: '/view/$id',
  path: '/view/$id',
  getParentRoute: () => AdminAdminNodesRoute,
} as any)
const AdminAdminServersViewIdIndexRoute =
  AdminAdminServersViewIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminServersViewIdRoute,
  } as any)
const AdminAdminNodesViewIdIndexRoute =
  AdminAdminNodesViewIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminNodesViewIdRoute,
  } as any)
const AdminAdminServersViewIdStartupRoute =
  AdminAdminServersViewIdStartupRouteImport.update({
    id: '/startup',
    path: '/startup',
    getParentRoute: () => AdminAdminServersViewIdRoute,
  } as any)
const AdminAdminServersViewIdMountsRoute =
  AdminAdminServersViewIdMountsRouteImport.update({
    id: '/mounts',
    path: '/mounts',
    getParentRoute: () => AdminAdminServersViewIdRoute,
  } as any)
const AdminAdminServersViewIdManageRoute =
  AdminAdminServersViewIdManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => AdminAdminServersViewIdRoute,
  } as any)
const AdminAdminServersViewIdDetailsRoute =
  AdminAdminServersViewIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => AdminAdminServersViewIdRoute,
  } as any)
const AdminAdminServersViewIdDeleteRoute =
  AdminAdminServersViewIdDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => AdminAdminServersViewIdRoute,
  } as any)
const AdminAdminServersViewIdDatabaseRoute =
  AdminAdminServersViewIdDatabaseRouteImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => AdminAdminServersViewIdRoute,
  } as any)
const AdminAdminServersViewIdBuildRoute =
  AdminAdminServersViewIdBuildRouteImport.update({
    id: '/build',
    path: '/build',
    getParentRoute: () => AdminAdminServersViewIdRoute,
  } as any)
const AdminAdminNodesViewIdSettingsRoute =
  AdminAdminNodesViewIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminAdminNodesViewIdRoute,
  } as any)
const AdminAdminNodesViewIdServersRoute =
  AdminAdminNodesViewIdServersRouteImport.update({
    id: '/servers',
    path: '/servers',
    getParentRoute: () => AdminAdminNodesViewIdRoute,
  } as any)
const AdminAdminNodesViewIdConfigurationRoute =
  AdminAdminNodesViewIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AdminAdminNodesViewIdRoute,
  } as any)
const AdminAdminNodesViewIdAllocationRoute =
  AdminAdminNodesViewIdAllocationRouteImport.update({
    id: '/allocation',
    path: '/allocation',
    getParentRoute: () => AdminAdminNodesViewIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/account': typeof AuthedAccountRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRouteWithChildren
  '/admin/activity': typeof AdminAdminActivityRoute
  '/admin/allocations': typeof AdminAdminAllocationsRoute
  '/admin/api': typeof AdminAdminApiRoute
  '/admin/databases': typeof AdminAdminDatabasesRoute
  '/admin/locations': typeof AdminAdminLocationsRoute
  '/admin/mounts': typeof AdminAdminMountsRoute
  '/admin/nests': typeof AdminAdminNestsRoute
  '/admin/nodes': typeof AdminAdminNodesRouteWithChildren
  '/admin/servers': typeof AdminAdminServersRouteWithChildren
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/account/activity': typeof AuthedAccountActivityRoute
  '/account/api': typeof AuthedAccountApiRoute
  '/account/ssh': typeof AuthedAccountSshRoute
  '/server/$id': typeof AuthedServerIdRouteWithChildren
  '/auth/login/checkpoint': typeof AuthLoginCheckpointRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/account/': typeof AuthedAccountIndexRoute
  '/admin/nodes/new': typeof AdminAdminNodesNewRoute
  '/server/$id/activity': typeof AuthedServerIdActivityRoute
  '/server/$id/backups': typeof AuthedServerIdBackupsRoute
  '/server/$id/databases': typeof AuthedServerIdDatabasesRoute
  '/server/$id/files': typeof AuthedServerIdFilesRoute
  '/server/$id/mods': typeof AuthedServerIdModsRoute
  '/server/$id/network': typeof AuthedServerIdNetworkRoute
  '/server/$id/schedules': typeof AuthedServerIdSchedulesRoute
  '/server/$id/settings': typeof AuthedServerIdSettingsRoute
  '/server/$id/shell': typeof AuthedServerIdShellRoute
  '/server/$id/startup': typeof AuthedServerIdStartupRoute
  '/server/$id/users': typeof AuthedServerIdUsersRoute
  '/admin/nodes/': typeof AdminAdminNodesIndexRoute
  '/admin/servers/': typeof AdminAdminServersIndexRoute
  '/server/$id/': typeof AuthedServerIdIndexRoute
  '/admin/nodes/view/$id': typeof AdminAdminNodesViewIdRouteWithChildren
  '/admin/servers/view/$id': typeof AdminAdminServersViewIdRouteWithChildren
  '/admin/nodes/view/$id/allocation': typeof AdminAdminNodesViewIdAllocationRoute
  '/admin/nodes/view/$id/configuration': typeof AdminAdminNodesViewIdConfigurationRoute
  '/admin/nodes/view/$id/servers': typeof AdminAdminNodesViewIdServersRoute
  '/admin/nodes/view/$id/settings': typeof AdminAdminNodesViewIdSettingsRoute
  '/admin/servers/view/$id/build': typeof AdminAdminServersViewIdBuildRoute
  '/admin/servers/view/$id/database': typeof AdminAdminServersViewIdDatabaseRoute
  '/admin/servers/view/$id/delete': typeof AdminAdminServersViewIdDeleteRoute
  '/admin/servers/view/$id/details': typeof AdminAdminServersViewIdDetailsRoute
  '/admin/servers/view/$id/manage': typeof AdminAdminServersViewIdManageRoute
  '/admin/servers/view/$id/mounts': typeof AdminAdminServersViewIdMountsRoute
  '/admin/servers/view/$id/startup': typeof AdminAdminServersViewIdStartupRoute
  '/admin/nodes/view/$id/': typeof AdminAdminNodesViewIdIndexRoute
  '/admin/servers/view/$id/': typeof AdminAdminServersViewIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRouteWithChildren
  '/admin/activity': typeof AdminAdminActivityRoute
  '/admin/allocations': typeof AdminAdminAllocationsRoute
  '/admin/api': typeof AdminAdminApiRoute
  '/admin/databases': typeof AdminAdminDatabasesRoute
  '/admin/locations': typeof AdminAdminLocationsRoute
  '/admin/mounts': typeof AdminAdminMountsRoute
  '/admin/nests': typeof AdminAdminNestsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/account/activity': typeof AuthedAccountActivityRoute
  '/account/api': typeof AuthedAccountApiRoute
  '/account/ssh': typeof AuthedAccountSshRoute
  '/auth/login/checkpoint': typeof AuthLoginCheckpointRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/admin': typeof AdminAdminIndexRoute
  '/account': typeof AuthedAccountIndexRoute
  '/admin/nodes/new': typeof AdminAdminNodesNewRoute
  '/server/$id/activity': typeof AuthedServerIdActivityRoute
  '/server/$id/backups': typeof AuthedServerIdBackupsRoute
  '/server/$id/databases': typeof AuthedServerIdDatabasesRoute
  '/server/$id/files': typeof AuthedServerIdFilesRoute
  '/server/$id/mods': typeof AuthedServerIdModsRoute
  '/server/$id/network': typeof AuthedServerIdNetworkRoute
  '/server/$id/schedules': typeof AuthedServerIdSchedulesRoute
  '/server/$id/settings': typeof AuthedServerIdSettingsRoute
  '/server/$id/shell': typeof AuthedServerIdShellRoute
  '/server/$id/startup': typeof AuthedServerIdStartupRoute
  '/server/$id/users': typeof AuthedServerIdUsersRoute
  '/admin/nodes': typeof AdminAdminNodesIndexRoute
  '/admin/servers': typeof AdminAdminServersIndexRoute
  '/server/$id': typeof AuthedServerIdIndexRoute
  '/admin/nodes/view/$id/allocation': typeof AdminAdminNodesViewIdAllocationRoute
  '/admin/nodes/view/$id/configuration': typeof AdminAdminNodesViewIdConfigurationRoute
  '/admin/nodes/view/$id/servers': typeof AdminAdminNodesViewIdServersRoute
  '/admin/nodes/view/$id/settings': typeof AdminAdminNodesViewIdSettingsRoute
  '/admin/servers/view/$id/build': typeof AdminAdminServersViewIdBuildRoute
  '/admin/servers/view/$id/database': typeof AdminAdminServersViewIdDatabaseRoute
  '/admin/servers/view/$id/delete': typeof AdminAdminServersViewIdDeleteRoute
  '/admin/servers/view/$id/details': typeof AdminAdminServersViewIdDetailsRoute
  '/admin/servers/view/$id/manage': typeof AdminAdminServersViewIdManageRoute
  '/admin/servers/view/$id/mounts': typeof AdminAdminServersViewIdMountsRoute
  '/admin/servers/view/$id/startup': typeof AdminAdminServersViewIdStartupRoute
  '/admin/nodes/view/$id': typeof AdminAdminNodesViewIdIndexRoute
  '/admin/servers/view/$id': typeof AdminAdminServersViewIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authed/account': typeof AuthedAccountRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_admin/admin/activity': typeof AdminAdminActivityRoute
  '/_admin/admin/allocations': typeof AdminAdminAllocationsRoute
  '/_admin/admin/api': typeof AdminAdminApiRoute
  '/_admin/admin/databases': typeof AdminAdminDatabasesRoute
  '/_admin/admin/locations': typeof AdminAdminLocationsRoute
  '/_admin/admin/mounts': typeof AdminAdminMountsRoute
  '/_admin/admin/nests': typeof AdminAdminNestsRoute
  '/_admin/admin/nodes': typeof AdminAdminNodesRouteWithChildren
  '/_admin/admin/servers': typeof AdminAdminServersRouteWithChildren
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_authed/account/activity': typeof AuthedAccountActivityRoute
  '/_authed/account/api': typeof AuthedAccountApiRoute
  '/_authed/account/ssh': typeof AuthedAccountSshRoute
  '/_authed/server/$id': typeof AuthedServerIdRouteWithChildren
  '/auth/login/checkpoint': typeof AuthLoginCheckpointRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authed/account/': typeof AuthedAccountIndexRoute
  '/_admin/admin/nodes/new': typeof AdminAdminNodesNewRoute
  '/_authed/server/$id/activity': typeof AuthedServerIdActivityRoute
  '/_authed/server/$id/backups': typeof AuthedServerIdBackupsRoute
  '/_authed/server/$id/databases': typeof AuthedServerIdDatabasesRoute
  '/_authed/server/$id/files': typeof AuthedServerIdFilesRoute
  '/_authed/server/$id/mods': typeof AuthedServerIdModsRoute
  '/_authed/server/$id/network': typeof AuthedServerIdNetworkRoute
  '/_authed/server/$id/schedules': typeof AuthedServerIdSchedulesRoute
  '/_authed/server/$id/settings': typeof AuthedServerIdSettingsRoute
  '/_authed/server/$id/shell': typeof AuthedServerIdShellRoute
  '/_authed/server/$id/startup': typeof AuthedServerIdStartupRoute
  '/_authed/server/$id/users': typeof AuthedServerIdUsersRoute
  '/_admin/admin/nodes/': typeof AdminAdminNodesIndexRoute
  '/_admin/admin/servers/': typeof AdminAdminServersIndexRoute
  '/_authed/server/$id/': typeof AuthedServerIdIndexRoute
  '/_admin/admin/nodes/view/$id': typeof AdminAdminNodesViewIdRouteWithChildren
  '/_admin/admin/servers/view/$id': typeof AdminAdminServersViewIdRouteWithChildren
  '/_admin/admin/nodes/view/$id/allocation': typeof AdminAdminNodesViewIdAllocationRoute
  '/_admin/admin/nodes/view/$id/configuration': typeof AdminAdminNodesViewIdConfigurationRoute
  '/_admin/admin/nodes/view/$id/servers': typeof AdminAdminNodesViewIdServersRoute
  '/_admin/admin/nodes/view/$id/settings': typeof AdminAdminNodesViewIdSettingsRoute
  '/_admin/admin/servers/view/$id/build': typeof AdminAdminServersViewIdBuildRoute
  '/_admin/admin/servers/view/$id/database': typeof AdminAdminServersViewIdDatabaseRoute
  '/_admin/admin/servers/view/$id/delete': typeof AdminAdminServersViewIdDeleteRoute
  '/_admin/admin/servers/view/$id/details': typeof AdminAdminServersViewIdDetailsRoute
  '/_admin/admin/servers/view/$id/manage': typeof AdminAdminServersViewIdManageRoute
  '/_admin/admin/servers/view/$id/mounts': typeof AdminAdminServersViewIdMountsRoute
  '/_admin/admin/servers/view/$id/startup': typeof AdminAdminServersViewIdStartupRoute
  '/_admin/admin/nodes/view/$id/': typeof AdminAdminNodesViewIdIndexRoute
  '/_admin/admin/servers/view/$id/': typeof AdminAdminServersViewIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/account'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/admin/activity'
    | '/admin/allocations'
    | '/admin/api'
    | '/admin/databases'
    | '/admin/locations'
    | '/admin/mounts'
    | '/admin/nests'
    | '/admin/nodes'
    | '/admin/servers'
    | '/admin/settings'
    | '/admin/users'
    | '/account/activity'
    | '/account/api'
    | '/account/ssh'
    | '/server/$id'
    | '/auth/login/checkpoint'
    | '/auth/reset-password/$token'
    | '/admin/'
    | '/account/'
    | '/admin/nodes/new'
    | '/server/$id/activity'
    | '/server/$id/backups'
    | '/server/$id/databases'
    | '/server/$id/files'
    | '/server/$id/mods'
    | '/server/$id/network'
    | '/server/$id/schedules'
    | '/server/$id/settings'
    | '/server/$id/shell'
    | '/server/$id/startup'
    | '/server/$id/users'
    | '/admin/nodes/'
    | '/admin/servers/'
    | '/server/$id/'
    | '/admin/nodes/view/$id'
    | '/admin/servers/view/$id'
    | '/admin/nodes/view/$id/allocation'
    | '/admin/nodes/view/$id/configuration'
    | '/admin/nodes/view/$id/servers'
    | '/admin/nodes/view/$id/settings'
    | '/admin/servers/view/$id/build'
    | '/admin/servers/view/$id/database'
    | '/admin/servers/view/$id/delete'
    | '/admin/servers/view/$id/details'
    | '/admin/servers/view/$id/manage'
    | '/admin/servers/view/$id/mounts'
    | '/admin/servers/view/$id/startup'
    | '/admin/nodes/view/$id/'
    | '/admin/servers/view/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/admin/activity'
    | '/admin/allocations'
    | '/admin/api'
    | '/admin/databases'
    | '/admin/locations'
    | '/admin/mounts'
    | '/admin/nests'
    | '/admin/settings'
    | '/admin/users'
    | '/account/activity'
    | '/account/api'
    | '/account/ssh'
    | '/auth/login/checkpoint'
    | '/auth/reset-password/$token'
    | '/admin'
    | '/account'
    | '/admin/nodes/new'
    | '/server/$id/activity'
    | '/server/$id/backups'
    | '/server/$id/databases'
    | '/server/$id/files'
    | '/server/$id/mods'
    | '/server/$id/network'
    | '/server/$id/schedules'
    | '/server/$id/settings'
    | '/server/$id/shell'
    | '/server/$id/startup'
    | '/server/$id/users'
    | '/admin/nodes'
    | '/admin/servers'
    | '/server/$id'
    | '/admin/nodes/view/$id/allocation'
    | '/admin/nodes/view/$id/configuration'
    | '/admin/nodes/view/$id/servers'
    | '/admin/nodes/view/$id/settings'
    | '/admin/servers/view/$id/build'
    | '/admin/servers/view/$id/database'
    | '/admin/servers/view/$id/delete'
    | '/admin/servers/view/$id/details'
    | '/admin/servers/view/$id/manage'
    | '/admin/servers/view/$id/mounts'
    | '/admin/servers/view/$id/startup'
    | '/admin/nodes/view/$id'
    | '/admin/servers/view/$id'
  id:
    | '__root__'
    | '/_admin'
    | '/_authed'
    | '/_admin/admin'
    | '/_authed/account'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/_authed/'
    | '/_admin/admin/activity'
    | '/_admin/admin/allocations'
    | '/_admin/admin/api'
    | '/_admin/admin/databases'
    | '/_admin/admin/locations'
    | '/_admin/admin/mounts'
    | '/_admin/admin/nests'
    | '/_admin/admin/nodes'
    | '/_admin/admin/servers'
    | '/_admin/admin/settings'
    | '/_admin/admin/users'
    | '/_authed/account/activity'
    | '/_authed/account/api'
    | '/_authed/account/ssh'
    | '/_authed/server/$id'
    | '/auth/login/checkpoint'
    | '/auth/reset-password/$token'
    | '/_admin/admin/'
    | '/_authed/account/'
    | '/_admin/admin/nodes/new'
    | '/_authed/server/$id/activity'
    | '/_authed/server/$id/backups'
    | '/_authed/server/$id/databases'
    | '/_authed/server/$id/files'
    | '/_authed/server/$id/mods'
    | '/_authed/server/$id/network'
    | '/_authed/server/$id/schedules'
    | '/_authed/server/$id/settings'
    | '/_authed/server/$id/shell'
    | '/_authed/server/$id/startup'
    | '/_authed/server/$id/users'
    | '/_admin/admin/nodes/'
    | '/_admin/admin/servers/'
    | '/_authed/server/$id/'
    | '/_admin/admin/nodes/view/$id'
    | '/_admin/admin/servers/view/$id'
    | '/_admin/admin/nodes/view/$id/allocation'
    | '/_admin/admin/nodes/view/$id/configuration'
    | '/_admin/admin/nodes/view/$id/servers'
    | '/_admin/admin/nodes/view/$id/settings'
    | '/_admin/admin/servers/view/$id/build'
    | '/_admin/admin/servers/view/$id/database'
    | '/_admin/admin/servers/view/$id/delete'
    | '/_admin/admin/servers/view/$id/details'
    | '/_admin/admin/servers/view/$id/manage'
    | '/_admin/admin/servers/view/$id/mounts'
    | '/_admin/admin/servers/view/$id/startup'
    | '/_admin/admin/nodes/view/$id/'
    | '/_admin/admin/servers/view/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRouteWithChildren
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/account/': {
      id: '/_authed/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthedAccountIndexRouteImport
      parentRoute: typeof AuthedAccountRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/auth/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/checkpoint': {
      id: '/auth/login/checkpoint'
      path: '/checkpoint'
      fullPath: '/auth/login/checkpoint'
      preLoaderRoute: typeof AuthLoginCheckpointRouteImport
      parentRoute: typeof AuthLoginRoute
    }
    '/_authed/server/$id': {
      id: '/_authed/server/$id'
      path: '/server/$id'
      fullPath: '/server/$id'
      preLoaderRoute: typeof AuthedServerIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/ssh': {
      id: '/_authed/account/ssh'
      path: '/ssh'
      fullPath: '/account/ssh'
      preLoaderRoute: typeof AuthedAccountSshRouteImport
      parentRoute: typeof AuthedAccountRoute
    }
    '/_authed/account/api': {
      id: '/_authed/account/api'
      path: '/api'
      fullPath: '/account/api'
      preLoaderRoute: typeof AuthedAccountApiRouteImport
      parentRoute: typeof AuthedAccountRoute
    }
    '/_authed/account/activity': {
      id: '/_authed/account/activity'
      path: '/activity'
      fullPath: '/account/activity'
      preLoaderRoute: typeof AuthedAccountActivityRouteImport
      parentRoute: typeof AuthedAccountRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/servers': {
      id: '/_admin/admin/servers'
      path: '/servers'
      fullPath: '/admin/servers'
      preLoaderRoute: typeof AdminAdminServersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/nodes': {
      id: '/_admin/admin/nodes'
      path: '/nodes'
      fullPath: '/admin/nodes'
      preLoaderRoute: typeof AdminAdminNodesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/nests': {
      id: '/_admin/admin/nests'
      path: '/nests'
      fullPath: '/admin/nests'
      preLoaderRoute: typeof AdminAdminNestsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/mounts': {
      id: '/_admin/admin/mounts'
      path: '/mounts'
      fullPath: '/admin/mounts'
      preLoaderRoute: typeof AdminAdminMountsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/locations': {
      id: '/_admin/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminAdminLocationsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/databases': {
      id: '/_admin/admin/databases'
      path: '/databases'
      fullPath: '/admin/databases'
      preLoaderRoute: typeof AdminAdminDatabasesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/api': {
      id: '/_admin/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminAdminApiRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/allocations': {
      id: '/_admin/admin/allocations'
      path: '/allocations'
      fullPath: '/admin/allocations'
      preLoaderRoute: typeof AdminAdminAllocationsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/activity': {
      id: '/_admin/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminAdminActivityRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authed/server/$id/': {
      id: '/_authed/server/$id/'
      path: '/'
      fullPath: '/server/$id/'
      preLoaderRoute: typeof AuthedServerIdIndexRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_admin/admin/servers/': {
      id: '/_admin/admin/servers/'
      path: '/'
      fullPath: '/admin/servers/'
      preLoaderRoute: typeof AdminAdminServersIndexRouteImport
      parentRoute: typeof AdminAdminServersRoute
    }
    '/_admin/admin/nodes/': {
      id: '/_admin/admin/nodes/'
      path: '/'
      fullPath: '/admin/nodes/'
      preLoaderRoute: typeof AdminAdminNodesIndexRouteImport
      parentRoute: typeof AdminAdminNodesRoute
    }
    '/_authed/server/$id/users': {
      id: '/_authed/server/$id/users'
      path: '/users'
      fullPath: '/server/$id/users'
      preLoaderRoute: typeof AuthedServerIdUsersRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/startup': {
      id: '/_authed/server/$id/startup'
      path: '/startup'
      fullPath: '/server/$id/startup'
      preLoaderRoute: typeof AuthedServerIdStartupRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/shell': {
      id: '/_authed/server/$id/shell'
      path: '/shell'
      fullPath: '/server/$id/shell'
      preLoaderRoute: typeof AuthedServerIdShellRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/settings': {
      id: '/_authed/server/$id/settings'
      path: '/settings'
      fullPath: '/server/$id/settings'
      preLoaderRoute: typeof AuthedServerIdSettingsRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/schedules': {
      id: '/_authed/server/$id/schedules'
      path: '/schedules'
      fullPath: '/server/$id/schedules'
      preLoaderRoute: typeof AuthedServerIdSchedulesRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/network': {
      id: '/_authed/server/$id/network'
      path: '/network'
      fullPath: '/server/$id/network'
      preLoaderRoute: typeof AuthedServerIdNetworkRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/mods': {
      id: '/_authed/server/$id/mods'
      path: '/mods'
      fullPath: '/server/$id/mods'
      preLoaderRoute: typeof AuthedServerIdModsRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/files': {
      id: '/_authed/server/$id/files'
      path: '/files'
      fullPath: '/server/$id/files'
      preLoaderRoute: typeof AuthedServerIdFilesRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/databases': {
      id: '/_authed/server/$id/databases'
      path: '/databases'
      fullPath: '/server/$id/databases'
      preLoaderRoute: typeof AuthedServerIdDatabasesRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/backups': {
      id: '/_authed/server/$id/backups'
      path: '/backups'
      fullPath: '/server/$id/backups'
      preLoaderRoute: typeof AuthedServerIdBackupsRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/activity': {
      id: '/_authed/server/$id/activity'
      path: '/activity'
      fullPath: '/server/$id/activity'
      preLoaderRoute: typeof AuthedServerIdActivityRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_admin/admin/nodes/new': {
      id: '/_admin/admin/nodes/new'
      path: '/new'
      fullPath: '/admin/nodes/new'
      preLoaderRoute: typeof AdminAdminNodesNewRouteImport
      parentRoute: typeof AdminAdminNodesRoute
    }
    '/_admin/admin/servers/view/$id': {
      id: '/_admin/admin/servers/view/$id'
      path: '/view/$id'
      fullPath: '/admin/servers/view/$id'
      preLoaderRoute: typeof AdminAdminServersViewIdRouteImport
      parentRoute: typeof AdminAdminServersRoute
    }
    '/_admin/admin/nodes/view/$id': {
      id: '/_admin/admin/nodes/view/$id'
      path: '/view/$id'
      fullPath: '/admin/nodes/view/$id'
      preLoaderRoute: typeof AdminAdminNodesViewIdRouteImport
      parentRoute: typeof AdminAdminNodesRoute
    }
    '/_admin/admin/servers/view/$id/': {
      id: '/_admin/admin/servers/view/$id/'
      path: '/'
      fullPath: '/admin/servers/view/$id/'
      preLoaderRoute: typeof AdminAdminServersViewIdIndexRouteImport
      parentRoute: typeof AdminAdminServersViewIdRoute
    }
    '/_admin/admin/nodes/view/$id/': {
      id: '/_admin/admin/nodes/view/$id/'
      path: '/'
      fullPath: '/admin/nodes/view/$id/'
      preLoaderRoute: typeof AdminAdminNodesViewIdIndexRouteImport
      parentRoute: typeof AdminAdminNodesViewIdRoute
    }
    '/_admin/admin/servers/view/$id/startup': {
      id: '/_admin/admin/servers/view/$id/startup'
      path: '/startup'
      fullPath: '/admin/servers/view/$id/startup'
      preLoaderRoute: typeof AdminAdminServersViewIdStartupRouteImport
      parentRoute: typeof AdminAdminServersViewIdRoute
    }
    '/_admin/admin/servers/view/$id/mounts': {
      id: '/_admin/admin/servers/view/$id/mounts'
      path: '/mounts'
      fullPath: '/admin/servers/view/$id/mounts'
      preLoaderRoute: typeof AdminAdminServersViewIdMountsRouteImport
      parentRoute: typeof AdminAdminServersViewIdRoute
    }
    '/_admin/admin/servers/view/$id/manage': {
      id: '/_admin/admin/servers/view/$id/manage'
      path: '/manage'
      fullPath: '/admin/servers/view/$id/manage'
      preLoaderRoute: typeof AdminAdminServersViewIdManageRouteImport
      parentRoute: typeof AdminAdminServersViewIdRoute
    }
    '/_admin/admin/servers/view/$id/details': {
      id: '/_admin/admin/servers/view/$id/details'
      path: '/details'
      fullPath: '/admin/servers/view/$id/details'
      preLoaderRoute: typeof AdminAdminServersViewIdDetailsRouteImport
      parentRoute: typeof AdminAdminServersViewIdRoute
    }
    '/_admin/admin/servers/view/$id/delete': {
      id: '/_admin/admin/servers/view/$id/delete'
      path: '/delete'
      fullPath: '/admin/servers/view/$id/delete'
      preLoaderRoute: typeof AdminAdminServersViewIdDeleteRouteImport
      parentRoute: typeof AdminAdminServersViewIdRoute
    }
    '/_admin/admin/servers/view/$id/database': {
      id: '/_admin/admin/servers/view/$id/database'
      path: '/database'
      fullPath: '/admin/servers/view/$id/database'
      preLoaderRoute: typeof AdminAdminServersViewIdDatabaseRouteImport
      parentRoute: typeof AdminAdminServersViewIdRoute
    }
    '/_admin/admin/servers/view/$id/build': {
      id: '/_admin/admin/servers/view/$id/build'
      path: '/build'
      fullPath: '/admin/servers/view/$id/build'
      preLoaderRoute: typeof AdminAdminServersViewIdBuildRouteImport
      parentRoute: typeof AdminAdminServersViewIdRoute
    }
    '/_admin/admin/nodes/view/$id/settings': {
      id: '/_admin/admin/nodes/view/$id/settings'
      path: '/settings'
      fullPath: '/admin/nodes/view/$id/settings'
      preLoaderRoute: typeof AdminAdminNodesViewIdSettingsRouteImport
      parentRoute: typeof AdminAdminNodesViewIdRoute
    }
    '/_admin/admin/nodes/view/$id/servers': {
      id: '/_admin/admin/nodes/view/$id/servers'
      path: '/servers'
      fullPath: '/admin/nodes/view/$id/servers'
      preLoaderRoute: typeof AdminAdminNodesViewIdServersRouteImport
      parentRoute: typeof AdminAdminNodesViewIdRoute
    }
    '/_admin/admin/nodes/view/$id/configuration': {
      id: '/_admin/admin/nodes/view/$id/configuration'
      path: '/configuration'
      fullPath: '/admin/nodes/view/$id/configuration'
      preLoaderRoute: typeof AdminAdminNodesViewIdConfigurationRouteImport
      parentRoute: typeof AdminAdminNodesViewIdRoute
    }
    '/_admin/admin/nodes/view/$id/allocation': {
      id: '/_admin/admin/nodes/view/$id/allocation'
      path: '/allocation'
      fullPath: '/admin/nodes/view/$id/allocation'
      preLoaderRoute: typeof AdminAdminNodesViewIdAllocationRouteImport
      parentRoute: typeof AdminAdminNodesViewIdRoute
    }
  }
}

interface AdminAdminNodesViewIdRouteChildren {
  AdminAdminNodesViewIdAllocationRoute: typeof AdminAdminNodesViewIdAllocationRoute
  AdminAdminNodesViewIdConfigurationRoute: typeof AdminAdminNodesViewIdConfigurationRoute
  AdminAdminNodesViewIdServersRoute: typeof AdminAdminNodesViewIdServersRoute
  AdminAdminNodesViewIdSettingsRoute: typeof AdminAdminNodesViewIdSettingsRoute
  AdminAdminNodesViewIdIndexRoute: typeof AdminAdminNodesViewIdIndexRoute
}

const AdminAdminNodesViewIdRouteChildren: AdminAdminNodesViewIdRouteChildren = {
  AdminAdminNodesViewIdAllocationRoute: AdminAdminNodesViewIdAllocationRoute,
  AdminAdminNodesViewIdConfigurationRoute:
    AdminAdminNodesViewIdConfigurationRoute,
  AdminAdminNodesViewIdServersRoute: AdminAdminNodesViewIdServersRoute,
  AdminAdminNodesViewIdSettingsRoute: AdminAdminNodesViewIdSettingsRoute,
  AdminAdminNodesViewIdIndexRoute: AdminAdminNodesViewIdIndexRoute,
}

const AdminAdminNodesViewIdRouteWithChildren =
  AdminAdminNodesViewIdRoute._addFileChildren(
    AdminAdminNodesViewIdRouteChildren,
  )

interface AdminAdminNodesRouteChildren {
  AdminAdminNodesNewRoute: typeof AdminAdminNodesNewRoute
  AdminAdminNodesIndexRoute: typeof AdminAdminNodesIndexRoute
  AdminAdminNodesViewIdRoute: typeof AdminAdminNodesViewIdRouteWithChildren
}

const AdminAdminNodesRouteChildren: AdminAdminNodesRouteChildren = {
  AdminAdminNodesNewRoute: AdminAdminNodesNewRoute,
  AdminAdminNodesIndexRoute: AdminAdminNodesIndexRoute,
  AdminAdminNodesViewIdRoute: AdminAdminNodesViewIdRouteWithChildren,
}

const AdminAdminNodesRouteWithChildren = AdminAdminNodesRoute._addFileChildren(
  AdminAdminNodesRouteChildren,
)

interface AdminAdminServersViewIdRouteChildren {
  AdminAdminServersViewIdBuildRoute: typeof AdminAdminServersViewIdBuildRoute
  AdminAdminServersViewIdDatabaseRoute: typeof AdminAdminServersViewIdDatabaseRoute
  AdminAdminServersViewIdDeleteRoute: typeof AdminAdminServersViewIdDeleteRoute
  AdminAdminServersViewIdDetailsRoute: typeof AdminAdminServersViewIdDetailsRoute
  AdminAdminServersViewIdManageRoute: typeof AdminAdminServersViewIdManageRoute
  AdminAdminServersViewIdMountsRoute: typeof AdminAdminServersViewIdMountsRoute
  AdminAdminServersViewIdStartupRoute: typeof AdminAdminServersViewIdStartupRoute
  AdminAdminServersViewIdIndexRoute: typeof AdminAdminServersViewIdIndexRoute
}

const AdminAdminServersViewIdRouteChildren: AdminAdminServersViewIdRouteChildren =
  {
    AdminAdminServersViewIdBuildRoute: AdminAdminServersViewIdBuildRoute,
    AdminAdminServersViewIdDatabaseRoute: AdminAdminServersViewIdDatabaseRoute,
    AdminAdminServersViewIdDeleteRoute: AdminAdminServersViewIdDeleteRoute,
    AdminAdminServersViewIdDetailsRoute: AdminAdminServersViewIdDetailsRoute,
    AdminAdminServersViewIdManageRoute: AdminAdminServersViewIdManageRoute,
    AdminAdminServersViewIdMountsRoute: AdminAdminServersViewIdMountsRoute,
    AdminAdminServersViewIdStartupRoute: AdminAdminServersViewIdStartupRoute,
    AdminAdminServersViewIdIndexRoute: AdminAdminServersViewIdIndexRoute,
  }

const AdminAdminServersViewIdRouteWithChildren =
  AdminAdminServersViewIdRoute._addFileChildren(
    AdminAdminServersViewIdRouteChildren,
  )

interface AdminAdminServersRouteChildren {
  AdminAdminServersIndexRoute: typeof AdminAdminServersIndexRoute
  AdminAdminServersViewIdRoute: typeof AdminAdminServersViewIdRouteWithChildren
}

const AdminAdminServersRouteChildren: AdminAdminServersRouteChildren = {
  AdminAdminServersIndexRoute: AdminAdminServersIndexRoute,
  AdminAdminServersViewIdRoute: AdminAdminServersViewIdRouteWithChildren,
}

const AdminAdminServersRouteWithChildren =
  AdminAdminServersRoute._addFileChildren(AdminAdminServersRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminActivityRoute: typeof AdminAdminActivityRoute
  AdminAdminAllocationsRoute: typeof AdminAdminAllocationsRoute
  AdminAdminApiRoute: typeof AdminAdminApiRoute
  AdminAdminDatabasesRoute: typeof AdminAdminDatabasesRoute
  AdminAdminLocationsRoute: typeof AdminAdminLocationsRoute
  AdminAdminMountsRoute: typeof AdminAdminMountsRoute
  AdminAdminNestsRoute: typeof AdminAdminNestsRoute
  AdminAdminNodesRoute: typeof AdminAdminNodesRouteWithChildren
  AdminAdminServersRoute: typeof AdminAdminServersRouteWithChildren
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminActivityRoute: AdminAdminActivityRoute,
  AdminAdminAllocationsRoute: AdminAdminAllocationsRoute,
  AdminAdminApiRoute: AdminAdminApiRoute,
  AdminAdminDatabasesRoute: AdminAdminDatabasesRoute,
  AdminAdminLocationsRoute: AdminAdminLocationsRoute,
  AdminAdminMountsRoute: AdminAdminMountsRoute,
  AdminAdminNestsRoute: AdminAdminNestsRoute,
  AdminAdminNodesRoute: AdminAdminNodesRouteWithChildren,
  AdminAdminServersRoute: AdminAdminServersRouteWithChildren,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthedAccountRouteChildren {
  AuthedAccountActivityRoute: typeof AuthedAccountActivityRoute
  AuthedAccountApiRoute: typeof AuthedAccountApiRoute
  AuthedAccountSshRoute: typeof AuthedAccountSshRoute
  AuthedAccountIndexRoute: typeof AuthedAccountIndexRoute
}

const AuthedAccountRouteChildren: AuthedAccountRouteChildren = {
  AuthedAccountActivityRoute: AuthedAccountActivityRoute,
  AuthedAccountApiRoute: AuthedAccountApiRoute,
  AuthedAccountSshRoute: AuthedAccountSshRoute,
  AuthedAccountIndexRoute: AuthedAccountIndexRoute,
}

const AuthedAccountRouteWithChildren = AuthedAccountRoute._addFileChildren(
  AuthedAccountRouteChildren,
)

interface AuthedServerIdRouteChildren {
  AuthedServerIdActivityRoute: typeof AuthedServerIdActivityRoute
  AuthedServerIdBackupsRoute: typeof AuthedServerIdBackupsRoute
  AuthedServerIdDatabasesRoute: typeof AuthedServerIdDatabasesRoute
  AuthedServerIdFilesRoute: typeof AuthedServerIdFilesRoute
  AuthedServerIdModsRoute: typeof AuthedServerIdModsRoute
  AuthedServerIdNetworkRoute: typeof AuthedServerIdNetworkRoute
  AuthedServerIdSchedulesRoute: typeof AuthedServerIdSchedulesRoute
  AuthedServerIdSettingsRoute: typeof AuthedServerIdSettingsRoute
  AuthedServerIdShellRoute: typeof AuthedServerIdShellRoute
  AuthedServerIdStartupRoute: typeof AuthedServerIdStartupRoute
  AuthedServerIdUsersRoute: typeof AuthedServerIdUsersRoute
  AuthedServerIdIndexRoute: typeof AuthedServerIdIndexRoute
}

const AuthedServerIdRouteChildren: AuthedServerIdRouteChildren = {
  AuthedServerIdActivityRoute: AuthedServerIdActivityRoute,
  AuthedServerIdBackupsRoute: AuthedServerIdBackupsRoute,
  AuthedServerIdDatabasesRoute: AuthedServerIdDatabasesRoute,
  AuthedServerIdFilesRoute: AuthedServerIdFilesRoute,
  AuthedServerIdModsRoute: AuthedServerIdModsRoute,
  AuthedServerIdNetworkRoute: AuthedServerIdNetworkRoute,
  AuthedServerIdSchedulesRoute: AuthedServerIdSchedulesRoute,
  AuthedServerIdSettingsRoute: AuthedServerIdSettingsRoute,
  AuthedServerIdShellRoute: AuthedServerIdShellRoute,
  AuthedServerIdStartupRoute: AuthedServerIdStartupRoute,
  AuthedServerIdUsersRoute: AuthedServerIdUsersRoute,
  AuthedServerIdIndexRoute: AuthedServerIdIndexRoute,
}

const AuthedServerIdRouteWithChildren = AuthedServerIdRoute._addFileChildren(
  AuthedServerIdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedServerIdRoute: typeof AuthedServerIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedServerIdRoute: AuthedServerIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthLoginRouteChildren {
  AuthLoginCheckpointRoute: typeof AuthLoginCheckpointRoute
}

const AuthLoginRouteChildren: AuthLoginRouteChildren = {
  AuthLoginCheckpointRoute: AuthLoginCheckpointRoute,
}

const AuthLoginRouteWithChildren = AuthLoginRoute._addFileChildren(
  AuthLoginRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRouteWithChildren,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
