/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAccountIndexRouteImport } from './routes/_authed/account/index'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/auth/reset-password.$token'
import { Route as AuthLoginCheckpointRouteImport } from './routes/auth/login.checkpoint'
import { Route as AuthedServerIdRouteImport } from './routes/_authed/server/$id'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminServersRouteImport } from './routes/_authed/admin/servers'
import { Route as AuthedAdminNodesRouteImport } from './routes/_authed/admin/nodes'
import { Route as AuthedAdminLocationsRouteImport } from './routes/_authed/admin/locations'
import { Route as AuthedAccountSshRouteImport } from './routes/_authed/account/ssh'
import { Route as AuthedAccountApiRouteImport } from './routes/_authed/account/api'
import { Route as AuthedAccountActivityRouteImport } from './routes/_authed/account/activity'
import { Route as AuthedServerIdIndexRouteImport } from './routes/_authed/server/$id/index'
import { Route as AuthedServerIdUsersRouteImport } from './routes/_authed/server/$id/users'
import { Route as AuthedServerIdStartupRouteImport } from './routes/_authed/server/$id/startup'
import { Route as AuthedServerIdShellRouteImport } from './routes/_authed/server/$id/shell'
import { Route as AuthedServerIdSettingsRouteImport } from './routes/_authed/server/$id/settings'
import { Route as AuthedServerIdSchedulesRouteImport } from './routes/_authed/server/$id/schedules'
import { Route as AuthedServerIdNetworkRouteImport } from './routes/_authed/server/$id/network'
import { Route as AuthedServerIdModsRouteImport } from './routes/_authed/server/$id/mods'
import { Route as AuthedServerIdFilesRouteImport } from './routes/_authed/server/$id/files'
import { Route as AuthedServerIdDatabasesRouteImport } from './routes/_authed/server/$id/databases'
import { Route as AuthedServerIdBackupsRouteImport } from './routes/_authed/server/$id/backups'
import { Route as AuthedServerIdActivityRouteImport } from './routes/_authed/server/$id/activity'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAccountIndexRoute = AuthedAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAccountRoute,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/auth/reset-password/$token',
  path: '/auth/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginCheckpointRoute = AuthLoginCheckpointRouteImport.update({
  id: '/checkpoint',
  path: '/checkpoint',
  getParentRoute: () => AuthLoginRoute,
} as any)
const AuthedServerIdRoute = AuthedServerIdRouteImport.update({
  id: '/server/$id',
  path: '/server/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminServersRoute = AuthedAdminServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminNodesRoute = AuthedAdminNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminLocationsRoute = AuthedAdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAccountSshRoute = AuthedAccountSshRouteImport.update({
  id: '/ssh',
  path: '/ssh',
  getParentRoute: () => AuthedAccountRoute,
} as any)
const AuthedAccountApiRoute = AuthedAccountApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthedAccountRoute,
} as any)
const AuthedAccountActivityRoute = AuthedAccountActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedAccountRoute,
} as any)
const AuthedServerIdIndexRoute = AuthedServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdUsersRoute = AuthedServerIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdStartupRoute = AuthedServerIdStartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdShellRoute = AuthedServerIdShellRouteImport.update({
  id: '/shell',
  path: '/shell',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdSettingsRoute = AuthedServerIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdSchedulesRoute = AuthedServerIdSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdNetworkRoute = AuthedServerIdNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdModsRoute = AuthedServerIdModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdFilesRoute = AuthedServerIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdDatabasesRoute = AuthedServerIdDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdBackupsRoute = AuthedServerIdBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthedServerIdRoute,
} as any)
const AuthedServerIdActivityRoute = AuthedServerIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedServerIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/account': typeof AuthedAccountRouteWithChildren
  '/admin': typeof AuthedAdminRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRouteWithChildren
  '/account/activity': typeof AuthedAccountActivityRoute
  '/account/api': typeof AuthedAccountApiRoute
  '/account/ssh': typeof AuthedAccountSshRoute
  '/admin/locations': typeof AuthedAdminLocationsRoute
  '/admin/nodes': typeof AuthedAdminNodesRoute
  '/admin/servers': typeof AuthedAdminServersRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/server/$id': typeof AuthedServerIdRouteWithChildren
  '/auth/login/checkpoint': typeof AuthLoginCheckpointRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/account/': typeof AuthedAccountIndexRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/server/$id/activity': typeof AuthedServerIdActivityRoute
  '/server/$id/backups': typeof AuthedServerIdBackupsRoute
  '/server/$id/databases': typeof AuthedServerIdDatabasesRoute
  '/server/$id/files': typeof AuthedServerIdFilesRoute
  '/server/$id/mods': typeof AuthedServerIdModsRoute
  '/server/$id/network': typeof AuthedServerIdNetworkRoute
  '/server/$id/schedules': typeof AuthedServerIdSchedulesRoute
  '/server/$id/settings': typeof AuthedServerIdSettingsRoute
  '/server/$id/shell': typeof AuthedServerIdShellRoute
  '/server/$id/startup': typeof AuthedServerIdStartupRoute
  '/server/$id/users': typeof AuthedServerIdUsersRoute
  '/server/$id/': typeof AuthedServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRouteWithChildren
  '/': typeof AuthedIndexRoute
  '/account/activity': typeof AuthedAccountActivityRoute
  '/account/api': typeof AuthedAccountApiRoute
  '/account/ssh': typeof AuthedAccountSshRoute
  '/admin/locations': typeof AuthedAdminLocationsRoute
  '/admin/nodes': typeof AuthedAdminNodesRoute
  '/admin/servers': typeof AuthedAdminServersRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/auth/login/checkpoint': typeof AuthLoginCheckpointRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/account': typeof AuthedAccountIndexRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/server/$id/activity': typeof AuthedServerIdActivityRoute
  '/server/$id/backups': typeof AuthedServerIdBackupsRoute
  '/server/$id/databases': typeof AuthedServerIdDatabasesRoute
  '/server/$id/files': typeof AuthedServerIdFilesRoute
  '/server/$id/mods': typeof AuthedServerIdModsRoute
  '/server/$id/network': typeof AuthedServerIdNetworkRoute
  '/server/$id/schedules': typeof AuthedServerIdSchedulesRoute
  '/server/$id/settings': typeof AuthedServerIdSettingsRoute
  '/server/$id/shell': typeof AuthedServerIdShellRoute
  '/server/$id/startup': typeof AuthedServerIdStartupRoute
  '/server/$id/users': typeof AuthedServerIdUsersRoute
  '/server/$id': typeof AuthedServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/account': typeof AuthedAccountRouteWithChildren
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/account/activity': typeof AuthedAccountActivityRoute
  '/_authed/account/api': typeof AuthedAccountApiRoute
  '/_authed/account/ssh': typeof AuthedAccountSshRoute
  '/_authed/admin/locations': typeof AuthedAdminLocationsRoute
  '/_authed/admin/nodes': typeof AuthedAdminNodesRoute
  '/_authed/admin/servers': typeof AuthedAdminServersRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/server/$id': typeof AuthedServerIdRouteWithChildren
  '/auth/login/checkpoint': typeof AuthLoginCheckpointRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/_authed/account/': typeof AuthedAccountIndexRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/server/$id/activity': typeof AuthedServerIdActivityRoute
  '/_authed/server/$id/backups': typeof AuthedServerIdBackupsRoute
  '/_authed/server/$id/databases': typeof AuthedServerIdDatabasesRoute
  '/_authed/server/$id/files': typeof AuthedServerIdFilesRoute
  '/_authed/server/$id/mods': typeof AuthedServerIdModsRoute
  '/_authed/server/$id/network': typeof AuthedServerIdNetworkRoute
  '/_authed/server/$id/schedules': typeof AuthedServerIdSchedulesRoute
  '/_authed/server/$id/settings': typeof AuthedServerIdSettingsRoute
  '/_authed/server/$id/shell': typeof AuthedServerIdShellRoute
  '/_authed/server/$id/startup': typeof AuthedServerIdStartupRoute
  '/_authed/server/$id/users': typeof AuthedServerIdUsersRoute
  '/_authed/server/$id/': typeof AuthedServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/account/activity'
    | '/account/api'
    | '/account/ssh'
    | '/admin/locations'
    | '/admin/nodes'
    | '/admin/servers'
    | '/admin/users'
    | '/server/$id'
    | '/auth/login/checkpoint'
    | '/auth/reset-password/$token'
    | '/account/'
    | '/admin/'
    | '/server/$id/activity'
    | '/server/$id/backups'
    | '/server/$id/databases'
    | '/server/$id/files'
    | '/server/$id/mods'
    | '/server/$id/network'
    | '/server/$id/schedules'
    | '/server/$id/settings'
    | '/server/$id/shell'
    | '/server/$id/startup'
    | '/server/$id/users'
    | '/server/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/forgot-password'
    | '/auth/login'
    | '/'
    | '/account/activity'
    | '/account/api'
    | '/account/ssh'
    | '/admin/locations'
    | '/admin/nodes'
    | '/admin/servers'
    | '/admin/users'
    | '/auth/login/checkpoint'
    | '/auth/reset-password/$token'
    | '/account'
    | '/admin'
    | '/server/$id/activity'
    | '/server/$id/backups'
    | '/server/$id/databases'
    | '/server/$id/files'
    | '/server/$id/mods'
    | '/server/$id/network'
    | '/server/$id/schedules'
    | '/server/$id/settings'
    | '/server/$id/shell'
    | '/server/$id/startup'
    | '/server/$id/users'
    | '/server/$id'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/account'
    | '/_authed/admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/_authed/'
    | '/_authed/account/activity'
    | '/_authed/account/api'
    | '/_authed/account/ssh'
    | '/_authed/admin/locations'
    | '/_authed/admin/nodes'
    | '/_authed/admin/servers'
    | '/_authed/admin/users'
    | '/_authed/server/$id'
    | '/auth/login/checkpoint'
    | '/auth/reset-password/$token'
    | '/_authed/account/'
    | '/_authed/admin/'
    | '/_authed/server/$id/activity'
    | '/_authed/server/$id/backups'
    | '/_authed/server/$id/databases'
    | '/_authed/server/$id/files'
    | '/_authed/server/$id/mods'
    | '/_authed/server/$id/network'
    | '/_authed/server/$id/schedules'
    | '/_authed/server/$id/settings'
    | '/_authed/server/$id/shell'
    | '/_authed/server/$id/startup'
    | '/_authed/server/$id/users'
    | '/_authed/server/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRouteWithChildren
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/account/': {
      id: '/_authed/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthedAccountIndexRouteImport
      parentRoute: typeof AuthedAccountRoute
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/auth/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/checkpoint': {
      id: '/auth/login/checkpoint'
      path: '/checkpoint'
      fullPath: '/auth/login/checkpoint'
      preLoaderRoute: typeof AuthLoginCheckpointRouteImport
      parentRoute: typeof AuthLoginRoute
    }
    '/_authed/server/$id': {
      id: '/_authed/server/$id'
      path: '/server/$id'
      fullPath: '/server/$id'
      preLoaderRoute: typeof AuthedServerIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/servers': {
      id: '/_authed/admin/servers'
      path: '/servers'
      fullPath: '/admin/servers'
      preLoaderRoute: typeof AuthedAdminServersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/nodes': {
      id: '/_authed/admin/nodes'
      path: '/nodes'
      fullPath: '/admin/nodes'
      preLoaderRoute: typeof AuthedAdminNodesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/locations': {
      id: '/_authed/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AuthedAdminLocationsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/account/ssh': {
      id: '/_authed/account/ssh'
      path: '/ssh'
      fullPath: '/account/ssh'
      preLoaderRoute: typeof AuthedAccountSshRouteImport
      parentRoute: typeof AuthedAccountRoute
    }
    '/_authed/account/api': {
      id: '/_authed/account/api'
      path: '/api'
      fullPath: '/account/api'
      preLoaderRoute: typeof AuthedAccountApiRouteImport
      parentRoute: typeof AuthedAccountRoute
    }
    '/_authed/account/activity': {
      id: '/_authed/account/activity'
      path: '/activity'
      fullPath: '/account/activity'
      preLoaderRoute: typeof AuthedAccountActivityRouteImport
      parentRoute: typeof AuthedAccountRoute
    }
    '/_authed/server/$id/': {
      id: '/_authed/server/$id/'
      path: '/'
      fullPath: '/server/$id/'
      preLoaderRoute: typeof AuthedServerIdIndexRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/users': {
      id: '/_authed/server/$id/users'
      path: '/users'
      fullPath: '/server/$id/users'
      preLoaderRoute: typeof AuthedServerIdUsersRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/startup': {
      id: '/_authed/server/$id/startup'
      path: '/startup'
      fullPath: '/server/$id/startup'
      preLoaderRoute: typeof AuthedServerIdStartupRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/shell': {
      id: '/_authed/server/$id/shell'
      path: '/shell'
      fullPath: '/server/$id/shell'
      preLoaderRoute: typeof AuthedServerIdShellRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/settings': {
      id: '/_authed/server/$id/settings'
      path: '/settings'
      fullPath: '/server/$id/settings'
      preLoaderRoute: typeof AuthedServerIdSettingsRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/schedules': {
      id: '/_authed/server/$id/schedules'
      path: '/schedules'
      fullPath: '/server/$id/schedules'
      preLoaderRoute: typeof AuthedServerIdSchedulesRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/network': {
      id: '/_authed/server/$id/network'
      path: '/network'
      fullPath: '/server/$id/network'
      preLoaderRoute: typeof AuthedServerIdNetworkRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/mods': {
      id: '/_authed/server/$id/mods'
      path: '/mods'
      fullPath: '/server/$id/mods'
      preLoaderRoute: typeof AuthedServerIdModsRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/files': {
      id: '/_authed/server/$id/files'
      path: '/files'
      fullPath: '/server/$id/files'
      preLoaderRoute: typeof AuthedServerIdFilesRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/databases': {
      id: '/_authed/server/$id/databases'
      path: '/databases'
      fullPath: '/server/$id/databases'
      preLoaderRoute: typeof AuthedServerIdDatabasesRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/backups': {
      id: '/_authed/server/$id/backups'
      path: '/backups'
      fullPath: '/server/$id/backups'
      preLoaderRoute: typeof AuthedServerIdBackupsRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
    '/_authed/server/$id/activity': {
      id: '/_authed/server/$id/activity'
      path: '/activity'
      fullPath: '/server/$id/activity'
      preLoaderRoute: typeof AuthedServerIdActivityRouteImport
      parentRoute: typeof AuthedServerIdRoute
    }
  }
}

interface AuthedAccountRouteChildren {
  AuthedAccountActivityRoute: typeof AuthedAccountActivityRoute
  AuthedAccountApiRoute: typeof AuthedAccountApiRoute
  AuthedAccountSshRoute: typeof AuthedAccountSshRoute
  AuthedAccountIndexRoute: typeof AuthedAccountIndexRoute
}

const AuthedAccountRouteChildren: AuthedAccountRouteChildren = {
  AuthedAccountActivityRoute: AuthedAccountActivityRoute,
  AuthedAccountApiRoute: AuthedAccountApiRoute,
  AuthedAccountSshRoute: AuthedAccountSshRoute,
  AuthedAccountIndexRoute: AuthedAccountIndexRoute,
}

const AuthedAccountRouteWithChildren = AuthedAccountRoute._addFileChildren(
  AuthedAccountRouteChildren,
)

interface AuthedAdminRouteChildren {
  AuthedAdminLocationsRoute: typeof AuthedAdminLocationsRoute
  AuthedAdminNodesRoute: typeof AuthedAdminNodesRoute
  AuthedAdminServersRoute: typeof AuthedAdminServersRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminLocationsRoute: AuthedAdminLocationsRoute,
  AuthedAdminNodesRoute: AuthedAdminNodesRoute,
  AuthedAdminServersRoute: AuthedAdminServersRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedServerIdRouteChildren {
  AuthedServerIdActivityRoute: typeof AuthedServerIdActivityRoute
  AuthedServerIdBackupsRoute: typeof AuthedServerIdBackupsRoute
  AuthedServerIdDatabasesRoute: typeof AuthedServerIdDatabasesRoute
  AuthedServerIdFilesRoute: typeof AuthedServerIdFilesRoute
  AuthedServerIdModsRoute: typeof AuthedServerIdModsRoute
  AuthedServerIdNetworkRoute: typeof AuthedServerIdNetworkRoute
  AuthedServerIdSchedulesRoute: typeof AuthedServerIdSchedulesRoute
  AuthedServerIdSettingsRoute: typeof AuthedServerIdSettingsRoute
  AuthedServerIdShellRoute: typeof AuthedServerIdShellRoute
  AuthedServerIdStartupRoute: typeof AuthedServerIdStartupRoute
  AuthedServerIdUsersRoute: typeof AuthedServerIdUsersRoute
  AuthedServerIdIndexRoute: typeof AuthedServerIdIndexRoute
}

const AuthedServerIdRouteChildren: AuthedServerIdRouteChildren = {
  AuthedServerIdActivityRoute: AuthedServerIdActivityRoute,
  AuthedServerIdBackupsRoute: AuthedServerIdBackupsRoute,
  AuthedServerIdDatabasesRoute: AuthedServerIdDatabasesRoute,
  AuthedServerIdFilesRoute: AuthedServerIdFilesRoute,
  AuthedServerIdModsRoute: AuthedServerIdModsRoute,
  AuthedServerIdNetworkRoute: AuthedServerIdNetworkRoute,
  AuthedServerIdSchedulesRoute: AuthedServerIdSchedulesRoute,
  AuthedServerIdSettingsRoute: AuthedServerIdSettingsRoute,
  AuthedServerIdShellRoute: AuthedServerIdShellRoute,
  AuthedServerIdStartupRoute: AuthedServerIdStartupRoute,
  AuthedServerIdUsersRoute: AuthedServerIdUsersRoute,
  AuthedServerIdIndexRoute: AuthedServerIdIndexRoute,
}

const AuthedServerIdRouteWithChildren = AuthedServerIdRoute._addFileChildren(
  AuthedServerIdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRouteWithChildren
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedServerIdRoute: typeof AuthedServerIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRouteWithChildren,
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedServerIdRoute: AuthedServerIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthLoginRouteChildren {
  AuthLoginCheckpointRoute: typeof AuthLoginCheckpointRoute
}

const AuthLoginRouteChildren: AuthLoginRouteChildren = {
  AuthLoginCheckpointRoute: AuthLoginCheckpointRoute,
}

const AuthLoginRouteWithChildren = AuthLoginRoute._addFileChildren(
  AuthLoginRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRouteWithChildren,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
